### PR TITLE
OneDot is not a thing anymore fyi

### PR DESCRIPTION
**Pull request by devxan**
### Resolves

Resolves #

### Changes

-   

### Agree to our policies

-   [ ] I agree to follow the [Code of Conduct](https://github.com/onedotprojects/auth/blob/issues/.github/CODE_OF_CONDUCT.md).
-   [ ] I agree to follow the [Contributing Guidelines](https://github.com/onedotprojects/auth/blob/issues/.github/CONTRIBUTING.md).

### TODO:

-   [ ] <!-->

### CODE REVIEW

**Comment by cobaltt7** [comment]
why would I give William credit

**Comment by devxan** [comment]
> why would I give William credit

cuz they worked on it

**Comment by cobaltt7** [comment]
not nearly enough to deserve anything

**Comment by devxan** [comment]
> not nearly enough to deserve anything

okay. I don't care

**Pull request closed without merging**
